version: '3.7'

services:
  corelight:
    build:
      context: container/
      args:
        MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY:-}

    image: corelight:latest
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./container/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
      - ./corelight-softsensor.conf:/etc/corelight-softsensor.conf
      - ./corelight-update/global.yaml:/etc/corelight-update/global.yaml
      - ./corelight-update/configs:/etc/corelight-update/configs
      - ./corelight-update/working:/var/corelight-update/working
      - ./corelight-update/files:/var/corelight-update/files
      - ./corelight-update/packages:/etc/corelight/packages
      - ./corelight-update/global/global-bundle:/etc/corelight-update/global/global-bundle
      - ./corelight-update/global/global-input:/etc/corelight-update/global/global-input
      - ./corelight-update/global/global-intel:/etc/corelight-update/global/global-intel
      - ./corelight-update/global/global-suricata:/etc/corelight-update/global/global-suricata
      - ./local.zeek:/etc/corelight/local.zeek
      - ./zeek-intel:/etc/corelight/intel
      - ./GeoIP.conf:/etc/corelight-update/global/GeoIP.conf
      - ./suricata-rules:/etc/corelight/suricata-rules
      - ./input_files:/etc/corelight/input_files
      - ./data:/var/corelight
    tmpfs:
      - /run/suricata
    environment:
      CORELIGHT_LICENSE: ${CORELIGHT_LICENSE:-FIX_ME}
      MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID:-}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY:-}
