version: '3.7'

services:
  corelight:
    build:
      context: container/

    image: corelight:latest
    restart: always
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./container/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
      - ./data/etc/corelight:/etc/corelight
      - ./data/etc/corelight-update:/etc/corelight-update
      - ./data/var/corelight:/var/corelight
      - ./data/var/corelight-update:/var/corelight-update
      - ./data/opt/corelight-update:/opt/corelight-update
      - ./data/geoip:/usr/share/GeoIP
      - ./data/var/log/corelight-update.log:/var/log/corelight-update.log
      - ./corelight-softsensor/corelight-softsensor.conf:/etc/corelight-softsensor.conf
      - ./corelight-update/global.yaml:/etc/corelight-update/global.yaml
      - ./corelight-update/db-config.yaml:/etc/corelight-update/configs/defaultPolicy/db-config.yaml
      - ./corelight-update/GeoIP.conf:/etc/corelight-update/global/GeoIP.conf
    tmpfs:
      - /run/suricata
    environment:
      CORELIGHT_LICENSE: ${CORELIGHT_LICENSE:-FIX_ME}
      CORELIGHT_UPDATE: ${CORELIGHT_UPDATE:-yes}
      MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID:-}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY:-}